language: ruby

sudo: required

matrix:
  include:
  - os: osx
    rvm: 2.3.0
    osx_image: xcode8.2
  - os: osx
    rvm: 2.3.0
    osx_image: xcode7.3

script:
- KITCHEN_YAML=.kitchen.localhost.yml bundle exec kitchen verify macosx

branches:
  only:
  - macosx
